name: Build Multiplatform project
on:
  push:
    branches:
      - main
      - feature/ci_setup
  pull_request:

jobs:
  build-multiplatform-project:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-12]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.1.0
      - name: Publish package
        uses: gradle/gradle-build-action@v3.0.0
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}